use std::env;
use std::fs;
use std::path::PathBuf;

/// Rust keywords that cannot be used as bare identifiers. Icon names that
/// snake-case into one of these must be emitted as raw identifiers (`r#...`).
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let icons_dir = manifest_dir.join("icons");
    if !icons_dir.is_dir() {
        panic!("icons directory not found at {}", icons_dir.display());
    }

    // Watch the whole folder so adding/removing/editing an SVG triggers a rebuild.
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut names: Vec<String> = fs::read_dir(&icons_dir)
        .unwrap_or_else(|e| {
            panic!(
                "failed to read icons directory {}: {e}",
                icons_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "svg").unwrap_or(false))
        .filter_map(|p| p.file_stem().map(|s| s.to_string_lossy().into_owned()))
        .collect();
    names.sort();

    let icons_dir_str = icons_dir.to_string_lossy().replace('\\', "/");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n\n");
    generated.push_str("use iced::advanced::svg::Handle;\n");
    generated.push_str("use iced::widget::Svg;\n\n");
    generated.push_str("/// The generated per-icon SVG widget functions.\n");
    generated.push_str("pub mod icon {\n");
    generated.push_str("    use super::*;\n\n");

    let mut bytes = String::new();
    bytes.push_str("/// The generated per-icon raw SVG bytes.\n");
    bytes.push_str("pub mod bytes {\n\n");

    let mut seen: Vec<String> = Vec::new();
    for name in &names {
        let fn_name = to_snake_case(name);
        // The bytes constant is derived from the unescaped snake name so it
        // stays a plain identifier even when the function is a raw identifier.
        let const_name = name.replace('-', "_").to_uppercase();

        // Detect collisions: two files mapping to the same identifier.
        if seen.contains(&fn_name) {
            panic!(
                "multiple SVGs in {} map to the generated identifier `{fn_name}`",
                icons_dir.display()
            );
        }
        seen.push(fn_name.clone());

        generated.push_str(&format!(
            "    /// Renders the Lucide `{name}` icon as an SVG widget.\n"
        ));
        generated.push_str(&format!("    pub fn {fn_name}() -> Svg<'static> {{\n"));
        generated.push_str(&format!(
            "        Svg::new(Handle::from_memory(include_bytes!(\"{icons_dir_str}/{name}.svg\").as_slice()))\n"
        ));
        generated.push_str("    }\n\n");

        bytes.push_str(&format!(
            "    /// The raw SVG bytes of the Lucide `{name}` icon.\n"
        ));
        bytes.push_str(&format!(
            "    pub const {const_name}: &[u8] = include_bytes!(\"{icons_dir_str}/{name}.svg\");\n\n"
        ));
    }

    generated.push_str("}\n");
    generated.push_str(&bytes);
    generated.push_str("}\n");

    let generated_path = out_dir.join("generated.rs");
    fs::write(&generated_path, generated)
        .unwrap_or_else(|e| panic!("failed to write generated.rs: {e}"));

    println!("cargo:rerun-if-changed=build.rs");
}

/// Converts a kebab-case icon name to a valid Rust identifier, escaping it as a
/// raw identifier (`r#...`) when it collides with a Rust keyword.
fn to_snake_case(name: &str) -> String {
    let snake = name.replace('-', "_");
    if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("r#{snake}")
    } else {
        snake
    }
}
