use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let config_path = manifest_dir.join("build.toml");
    let config = fs::read_to_string(&config_path).unwrap_or_else(|e| {
        panic!(
            "failed to read build.toml at {}: {e}",
            config_path.display()
        )
    });

    let config: Config =
        toml::from_str(&config).unwrap_or_else(|e| panic!("failed to parse build.toml: {e}"));

    let icons_dir = manifest_dir.join("icons");
    let icons_dir_str = icons_dir.to_string_lossy().replace('\\', "/");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n\n");
    generated.push_str("use iced::advanced::svg::Handle;\n");
    generated.push_str("use iced::widget::Svg;\n\n");
    generated.push_str("/// The generated per-icon SVG widget functions.\n");
    generated.push_str("pub mod icon {\n");
    generated.push_str("    use super::*;\n\n");

    let mut bytes = String::new();
    bytes.push_str("/// The generated per-icon raw SVG bytes.\n");
    bytes.push_str("pub mod bytes {\n\n");

    for name in &config.icons {
        let svg_path = icons_dir.join(format!("{name}.svg"));
        if !svg_path.exists() {
            panic!(
                "icon '{name}' listed in build.toml has no matching file at {}",
                svg_path.display()
            );
        }
        let fn_name = to_snake_case(name);
        let const_name = fn_name.to_uppercase();
        generated.push_str(&format!(
            "    /// Renders the Lucide `{name}` icon as an SVG widget.\n"
        ));
        generated.push_str(&format!("    pub fn {fn_name}() -> Svg<'static> {{\n"));
        generated.push_str(&format!(
            "        Svg::new(Handle::from_memory(include_bytes!(\"{icons_dir_str}/{name}.svg\").as_slice()))\n"
        ));
        generated.push_str("    }\n\n");

        bytes.push_str(&format!(
            "    /// The raw SVG bytes of the Lucide `{name}` icon.\n"
        ));
        bytes.push_str(&format!(
            "    pub const {const_name}: &[u8] = include_bytes!(\"{icons_dir_str}/{name}.svg\");\n\n"
        ));
    }

    generated.push_str("}\n");
    generated.push_str(&bytes);
    generated.push_str("}\n");

    let generated_path = out_dir.join("generated.rs");
    fs::write(&generated_path, generated)
        .unwrap_or_else(|e| panic!("failed to write generated.rs: {e}"));

    println!("cargo:rerun-if-changed=build.toml");
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=build.rs");
}

#[derive(serde::Deserialize)]
struct Config {
    icons: Vec<String>,
}

fn to_snake_case(name: &str) -> String {
    name.replace('-', "_")
}
