//! Build-script helpers for registering custom icons from a folder.
//!
//! Cargo build scripts are isolated: a dependency's `build.rs` cannot see the
//! consumer's source tree. So custom icons are generated by the *consumer's*
//! own build script, which calls [`register_icons`]. That function scans a
//! folder of SVGs, writes a `custom_icons.rs` into the consumer's `OUT_DIR`,
//! and sets `LUCIDE_ICED_CUSTOM_ICONS` so the consumer can `include!` it.
//!
//! # Example
//!
//! In the consumer's `build.rs`:
//!
//! ```no_run
//! fn main() {
//!     lucide_iced::build::register_icons("icons/custom");
//! }
//! ```
//!
//! In the consumer's crate:
//!
//! ```ignore
//! pub mod custom_icons {
//!     include!(env!("LUCIDE_ICED_CUSTOM_ICONS"));
//! }
//! ```
//!
//! Every `.svg` in the folder then becomes `custom_icons::icon::<name>()` and
//! `custom_icons::bytes::<NAME>`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Rust keywords that cannot be used as bare identifiers. Icon names that
/// snake-case into one of these must be emitted as raw identifiers (`r#...`).
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

/// Scans `folder` for `.svg` files and generates a `custom_icons.rs` module.
///
/// `folder` is resolved relative to the consumer's `CARGO_MANIFEST_DIR`. The
/// generated file is written to the consumer's `OUT_DIR` and its path is
/// exposed as the `LUCIDE_ICED_CUSTOM_ICONS` env var (via `cargo:rustc-env`),
/// so the consumer can `include!(env!("LUCIDE_ICED_CUSTOM_ICONS"))`.
///
/// The folder is watched with `cargo:rerun-if-changed`, so adding, removing, or
/// editing an SVG triggers a rebuild.
///
/// # Panics
///
/// Panics (failing the build) if the folder does not exist, or if two SVGs map
/// to the same generated identifier (for example `foo-bar.svg` and
/// `foo_bar.svg` both become `foo_bar`).
pub fn register_icons(folder: &str) {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let dir = if Path::new(folder).is_absolute() {
        PathBuf::from(folder)
    } else {
        manifest_dir.join(folder)
    };

    if !dir.is_dir() {
        panic!(
            "lucide_iced::build::register_icons: folder does not exist: {}",
            dir.display()
        );
    }

    // Watch the folder so icon changes trigger a rebuild.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("failed to read icon folder {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "svg").unwrap_or(false))
        .collect();
    entries.sort();

    let generated = generate(&dir, &entries);

    let out_path = out_dir.join("custom_icons.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

    // Expose the path so the consumer can `include!(env!("LUCIDE_ICED_CUSTOM_ICONS"))`.
    println!(
        "cargo:rustc-env=LUCIDE_ICED_CUSTOM_ICONS={}",
        out_path.display()
    );
}

/// Builds the `custom_icons.rs` source for the given SVG files.
fn generate(dir: &Path, entries: &[PathBuf]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by lucide_iced::build::register_icons - do not edit\n\n");
    out.push_str("pub mod icon {\n");

    let mut bytes = String::new();
    bytes.push_str("pub mod bytes {\n");

    let mut seen: Vec<String> = Vec::new();
    for path in entries {
        let name = path.file_stem().unwrap().to_string_lossy().into_owned();
        let fn_name = to_snake_case(&name);
        let const_name = name.replace('-', "_").to_uppercase();

        // Detect collisions: two files mapping to the same identifier.
        if seen.contains(&fn_name) {
            panic!(
                "lucide_iced::build::register_icons: multiple SVGs map to the \
                 generated identifier `{fn_name}` in {}",
                dir.display()
            );
        }
        seen.push(fn_name.clone());

        let abs = path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    /// Renders the custom `{name}` icon as an SVG widget.\n"
        ));
        out.push_str(&format!(
            "    pub fn {fn_name}() -> lucide_iced::Svg<'static> {{\n"
        ));
        out.push_str(&format!(
            "        lucide_iced::Svg::new(lucide_iced::Handle::from_memory(include_bytes!(\"{abs}\").as_slice()))\n"
        ));
        out.push_str("    }\n\n");

        bytes.push_str(&format!(
            "    /// The raw SVG bytes of the custom `{name}` icon.\n"
        ));
        bytes.push_str(&format!(
            "    pub const {const_name}: &[u8] = include_bytes!(\"{abs}\");\n\n"
        ));
    }

    out.push_str("}\n");
    out.push_str(&bytes);
    out.push_str("}\n");
    out
}

/// Converts a kebab-case icon name to a valid Rust identifier, escaping it as a
/// raw identifier (`r#...`) when it collides with a Rust keyword.
fn to_snake_case(name: &str) -> String {
    let snake = name.replace('-', "_");
    if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("r#{snake}")
    } else {
        snake
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn write_svg(dir: &Path, name: &str) -> PathBuf {
        let path = dir.join(format!("{name}.svg"));
        fs::write(
            &path,
            "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'></svg>",
        )
        .unwrap();
        path
    }

    #[test]
    fn to_snake_case_escapes_keywords() {
        assert_eq!(to_snake_case("heart"), "heart");
        assert_eq!(to_snake_case("trash-2"), "trash_2");
        assert_eq!(to_snake_case("box"), "r#box");
        assert_eq!(to_snake_case("move"), "r#move");
        assert_eq!(to_snake_case("type"), "r#type");
    }

    #[test]
    fn generate_emits_icon_and_bytes_modules() {
        let dir = tempfile_dir();
        let heart = write_svg(&dir, "heart");
        let trash = write_svg(&dir, "trash-2");

        let code = generate(&dir, &[heart, trash]);

        assert!(code.contains("pub mod icon"));
        assert!(code.contains("pub mod bytes"));
        assert!(code.contains("pub fn heart() -> lucide_iced::Svg<'static>"));
        assert!(code.contains("pub fn trash_2() -> lucide_iced::Svg<'static>"));
        assert!(code.contains("pub const HEART: &[u8]"));
        assert!(code.contains("pub const TRASH_2: &[u8]"));
        // The generated code must reference the re-exported types, not `iced`
        // directly, so the consumer does not need a direct `iced` dependency.
        assert!(!code.contains("iced::widget::Svg"));
    }

    #[test]
    #[should_panic(expected = "multiple SVGs map to the generated identifier")]
    fn generate_detects_collisions() {
        let dir = tempfile_dir();
        // `foo-bar.svg` and `foo_bar.svg` both map to `foo_bar`.
        let a = write_svg(&dir, "foo-bar");
        let b = write_svg(&dir, "foo_bar");
        let _ = generate(&dir, &[a, b]);
    }

    #[test]
    fn generate_escapes_keyword_icons() {
        let dir = tempfile_dir();
        let box_icon = write_svg(&dir, "box");
        let code = generate(&dir, &[box_icon]);
        assert!(code.contains("pub fn r#box() -> lucide_iced::Svg<'static>"));
        assert!(code.contains("pub const BOX: &[u8]"));
    }

    /// Creates a unique temp dir for a test and removes it on drop.
    fn tempfile_dir() -> TempDir {
        let dir = std::env::temp_dir().join(format!(
            "lucide_iced_build_test_{}_{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        TempDir(dir)
    }

    struct TempDir(PathBuf);

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    impl std::ops::Deref for TempDir {
        type Target = Path;
        fn deref(&self) -> &Path {
            &self.0
        }
    }
}
